### PR TITLE
Lossless images optimization

### PR DESCRIPTION
**Pull request by FlipFloop**

### CODE REVIEW

**Comment by FlipFloop** [comment]
Let me know if more images are added so I can do this again

**Comment by copernicus-mogley** [comment]
That's great! I'm adding all of the latest logos and icons now, including graphics for each of the network upgrades. Thanks for your help!

**Comment by FlipFloop** [comment]
Tell me when I should pull!

**Comment by copernicus-mogley** [comment]
The new graphics are merged now. I put them in a new folder so your previous work didn't get overwritten and we can keep the old versions for fun and history :)

**Pull request merged**
